server:
  port: 18002                     # mapper映射文件
    
spring:
  application:
    name: provider-student
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:17001/eureka
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-student18002
    prefer-ip-address: true     #访问路径可以显示IP地址     



info: 
  app.name: provider-student
  company.name: www.jcohy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: "*"