= 目标

您将构建一个应用程序，将使用 Nacos + Seata 来创建分布式应用

== 准备

* 15 分钟
* 一个你喜欢的文本编辑器或 IDE
* JDK 1.8 以上
* https://software.jcohy.com/linux/nacos-server-1.3.2.tar.gz[Nacos 1.3.2 Linux] ，https://software.jcohy.com/windows/nacos-server-1.3.2.zip[Nacos 1.3.2 Windows]
* https://software.jcohy.com/linux/seata-server-1.4.2.tar.gz[Seata 1.4.2 Linux]，https://software.jcohy.com/windows/seata-server-1.4.2.zip[Seata 1.4.2 Windows]
* Gradle 6+ 或 Maven 3.2+
* 您还可以将代码直接导入到您的 IDE 中：
** Spring Tool Suite (STS)
** IntelliJ IDEA
** VSCode

== 开发

与大多数 Spring 入门指南一样，您可以从头开始并完成每个步骤，也可以绕过您已经熟悉的基本设置步骤。 无论哪种方式，您最终都会得到有效的代码。

== 下载安装并启动 Nacos

. 下载并解压 https://software.jcohy.com/linux/nacos-server-1.3.2.tar.gz[Nacos 1.3.2 Linux] 或 https://software.jcohy.com/windows/nacos-server-1.3.2.zip[Nacos 1.3.2 Windows]
. 进入到解压目录中的 `bin` 文件夹下，使用 `./startup.sh -m standalone`（Linux） 或 `startup.cmd -m standalone`（Windows） 启动服务器
. 打开 `http://localhost:8848/nacos`。默认账号密码为 `nacos`

更多请参考 https://nacos.io/zh-cn/docs/quick-start.html[Nacos 快速开始]

https://github.com/alibaba/spring-cloud-alibaba/blob/2021.x/spring-cloud-alibaba-docs/src/main/asciidoc-zh/sca-upgrade-guide.adoc#spring-cloud-alibaba-2021010-%E5%8D%87%E7%BA%A7%E6%8C%87%E5%8D%97[Nacos 升级指南]

=== 下载安装并启动 Seata Server

. 下载并解压 https://software.jcohy.com/linux/seata-server-1.4.2.tar.gz[Seata 1.4.2 Linux]，https://software.jcohy.com/windows/seata-server-1.4.2.zip[Seata 1.4.2 Windows]
. 修改 seata 配置文件 `$seata_server_home/conf/registry.conf`，`$seata_server_home` 这是是 seata server 的解压目录。
. 在 `conf` 目录下添加 `nacos-config.txt` 文件。可以通过官方提供的 https://github.com/seata/seata/tree/1.4.2/script/config-center/nacos[脚本执行]。
. 在创建应用程序客户端时，在 `yaml` 或 `properties` 文件中指定以下配置:
[source,yaml]
----
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
  tx-service-group: my_test_tx_group
----

NOTE: `my_test_tx_group` 组和 nacos-config.txt 中的配置的 `service.vgroup_mapping..${your-service-gruop}=default` 要一致。

项目所需的配置文件在 https://github.com/jcohy-sample/spring-sample/tree/4af7c0375732e469f8d4ca461255a668e54beb24/spring-cloud/spring-cloud-provider/conf[目录下]。

=== 创建服务

一次分别创建 `account-service-19001`， `order-service-19003`， `storage-service-19004`， `business-service-19002` 服务。

=== 创建一个 Application 类

在启动类上需要加上 `@EnableTransactionManagerServer` 注解

[source,java]
----
@SpringBootApplication
@EnableDiscoveryClient
@EnableFeignClients
public class BusinessProvider19002 {
    public static void main(String[] args) {
        SpringApplication.run(BusinessProvider19002.class, args);
    }
}
----

`@SpringBootApplication` 是一个简便的注解，它添加了以下所有内容：

* `@Configuration`：将类标记为应用程序上下文的 bean 定义源。
* `@EnableAutoConfiguration`：告诉 Spring Boot 开始添加基于类路径设置、其他 bean 和各种属性设置的 beans。例如，如果 spring-webmvc 在类路径上，则此注解将应用程序标记为 Web 应用程序并激活关键行为，例如设置 `DispatcherServlet`。
* `@ComponentScan`：告诉 Spring 在 `com/jcohy/sample/spring_cloud/tm` 包中寻找其他组件、配置和服务，让它找到控制器。

`@EnableDiscoveryClient` 注解开启服务注册发现。
`@EnableFeignClients` 启用 feign 客户端。

== 创建 Provider

`@RefreshScope` : 动态刷新
`GlobalTransactional` : 启用全局事务支持

== 运行

. 启动 Nacos 注册中心
. 启动四个服务  `account-service-19001`， `order-service-19003`， `storage-service-19004`， `business-service-19002`

== 测试

1、 购买下单，模拟全局事务提交

[source,http]
----
GET http://localhost:19002/purchase/commit
----

2、购买下单，模拟全局事务回滚

[source,http]
----
GET http://localhost:18002/student/name/赵雷
----

返回结果

[source,json]
----
GET http://localhost:19002/purchase/rollback
----

== 源码

https://github.com/jcohy-sample/spring-sample/tree/main/spring-cloud/spring-cloud-provider[源码] 和 https://github.com/jcohy-sample/spring-sample/blob/main/spring-cloud/spring-cloud-provider/http/provider.http[http 请求文件]


