server:
  port: 8090

spring:
  application:
    name: auth-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/resourceserver-introspection?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: <<username>> # update user
    password: <<password>> # update password
  sql:
    init:
      mode: always
      schema-locations: classpath:db/oauth2-introspection-schema.sql
