
server:
  port: 19002

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        exclude: "*"

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      username: "nacos"
      password: "nacos"