
server:
  port: 19002

spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        exclude: "*"
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: root
    password: test
#  sql:
#    init:
#      schema-locations: classpath:db/schema-h2.sql
#      data-locations: classpath:db/data-h2.sql
seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group : "SEATA_GROUP"
      username: "nacos"
      password: "nacos"
  tx-service-group: my_test_tx_group