= 目标

您将构建一个应用程序，将使用 Eureka + txlcn 来管理分布式事务

== 准备

* 15 分钟
* 一个你喜欢的文本编辑器或 IDE
* JDK 1.8 以上
* Mysql 数据库
* Gradle 4+ 或 Maven 3.2+
* 您还可以将代码直接导入到您的 IDE 中：
** Spring Tool Suite (STS)
** IntelliJ IDEA
** VSCode

== 开发

与大多数 Spring 入门指南一样，您可以从头开始并完成每个步骤，也可以绕过您已经熟悉的基本设置步骤。 无论哪种方式，您最终都会得到有效的代码。

== 创建 TM 工程 （txlcn-tm-18004）

=== 定义 Schema

TM 需要 mysql 数据库及 redis，所以需要事先准备 mysql 库和 redis，目前 lcn 插件包不支持 yaml，所以使用 properties：

[source,sql]
----
DROP SCHEMA IF EXISTS tx-manager;
CREATE SCHEMA tx-manager;
----

=== 创建配置文件

[source,properties]
----
##################
# 这个是启动本服务的配置文件，其它的 application-xxx.properties 是开发者的个性化配置，不用关心。
# 你可以在 https://txlcn.org/zh-cn/docs/setting/manager.html 看到所有的个性化配置
#################

server.port=18004
spring.application.name=txlcn-tm

# JDBC 数据库配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tx-manager?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
spring.datasource.username=root
spring.datasource.password=jcohy1203

# create:每次运行该程序，没有表格会新建表格，表内有数据会清空
# create-drop:每次程序结束的时候会清空表
# update:每次运行程序，没有表格会新建表格，表内有数据不会清空，只会更新
# validate:运行程序会校验数据与数据库的字段类型是否相同，不同会报错
# 第一次运行可以设置为: create, 为TM创建持久化数据库表
spring.jpa.hibernate.ddl-auto=create

# TM监听IP. 默认为 127.0.0.1
tx-lcn.manager.host=127.0.0.1

# TM监听Socket端口. 默认为 ${server.port} - 100
tx-lcn.manager.port=8070

# 数据库方言
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect

# 心跳检测时间(ms). 默认为 300000
tx-lcn.manager.heart-time=300000

# 分布式事务执行总时间(ms). 默认为36000
tx-lcn.manager.dtx-time=8000

# 参数延迟删除时间单位ms  默认为dtx-time值
#tx-lcn.message.netty.attr-delay-time=${tx-lcn.manager.dtx-time}

# 事务处理并发等级. 默认为机器逻辑核心数5倍
#tx-lcn.manager.concurrent-level=160

# TM后台登陆密码，默认值为codingapi
#tx-lcn.manager.admin-key=codingapi

# 分布式事务锁超时时间 默认为-1，当-1时会用tx-lcn.manager.dtx-time的时间
#tx-lcn.manager.dtx-lock-time=${tx-lcn.manager.dtx-time}

# 雪花算法的sequence位长度，默认为12位.
#tx-lcn.manager.seq-len=12

# 异常回调开关。开启时请制定ex-url
#tx-lcn.manager.ex-url-enabled=false

# 事务异常通知(任何http协议地址。未指定协议时，为TM提供内置功能接口)。默认是邮件通知
tx-lcn.manager.ex-url=/provider/email-to/jia_chao23@126.com



# 开启日志,默认为false
tx-lcn.logger.enabled=true
tx-lcn.logger.driver-class-name=${spring.datasource.driver-class-name}
tx-lcn.logger.jdbc-url=${spring.datasource.url}
tx-lcn.logger.username=${spring.datasource.username}
tx-lcn.logger.password=${spring.datasource.password}

# redis 的设置信息. 线上请用 Redis Cluster
#spring.redis.host=127.0.0.1
#spring.redis.port=6379
#spring.redis.password=
----

=== 创建一个 Application 类

在启动类上需要加上 `@EnableTransactionManagerServer` 注解

[source,java]
----
package com.jcohy.sample.spring_cloud.tm;

import com.codingapi.txlcn.tm.config.EnableTransactionManagerServer;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
@EnableTransactionManagerServer
public class TMApplication18004 {

    public static void main(String[] args) {
        SpringApplication.run(TMApplication18004.class, args);
    }
}
----

`@SpringBootApplication` 是一个简便的注解，它添加了以下所有内容：

* `@Configuration`：将类标记为应用程序上下文的 bean 定义源。
* `@EnableAutoConfiguration`：告诉 Spring Boot 开始添加基于类路径设置、其他 bean 和各种属性设置的 beans。例如，如果 spring-webmvc 在类路径上，则此注解将应用程序标记为 Web 应用程序并激活关键行为，例如设置 `DispatcherServlet`。
* `@ComponentScan`：告诉 Spring 在 `com/jcohy/sample/spring_cloud/tm` 包中寻找其他组件、配置和服务，让它找到控制器。

`@EnableTransactionManagerServer` 注解开启 TM 事务支持。

== 创建 Provider

=== 创建课程服务

在启动类上启用支持事务支持

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
include::{spring-cloud-code}/spring-cloud-provider-tm/course-service-18001/src/main/java/com/jcohy/sample/spring_cloud/provider/course/CourseProvider18001.java[]
----

在使用事务的方法上添加 `@LcnTransaction` 注解

[source,java,indent=0,subs="verbatim,quotes",role="primary"]
.Java
----
include::{spring-cloud-code}/spring-cloud-provider-tm/course-service-18001/src/main/java/com/jcohy/sample/spring_cloud/provider/course/servoce/impl/CourseServiceImpl.java[tag=code]
----

可以通过 http://localhost:端口号/h2-console 访问 h2 数据库。可以在项目启动过程中找到连接 url

[source,text]
----
2022-12-13 15:42:21.060  INFO 3028 --- [           main] o.s.b.a.h2.H2ConsoleAutoConfiguration    : H2 console available at '/h2-console'. Database available at 'jdbc:h2:mem:095170ca-7550-4fe6-9a3b-0979e66e175b'
----

=== 创建其他提供者

如上，创建 student 和 teacher 服务

== 运行

. 启动注册中心，spring-cloud-eureka-sample-17001 。端口号为 17001
. 启动 TM，txlcn-tm-18004 端口号为 18004
. 启动三个服务 `course-service-18001` ,`student-service-18002` ,`teacher-service-18003`

== 测试

1、添加学生成绩

[source,http]
----
POST http://localhost:18002/student/score/add
Content-Type: application/json

{
  "sname": "赵雷",
  "mapList": [
    {
      "cname": "语文",
      "tname": "张三",
      "score": 69
    },
    {
      "cname": "数学",
      "tname": "李四",
      "score": 89
    },
    {
      "cname": "英语",
      "tname": "王五",
      "score": 66
    }
  ]
}
----

2、查看

[source,http]
----
GET http://localhost:18002/student/name/赵雷
----

返回结果

[source,json]
----
{
  "sname": "赵雷",
  "mapList": [
    {
      "score": 69,
      "cname": "语文",
      "tname": "张三"
    },
    {
      "score": 89,
      "cname": "数学",
      "tname": "李四"
    },
    {
      "score": 66,
      "cname": "英语",
      "tname": "王五"
    }
  ]
}
----

3、现在让我模拟异常请求，在第一步的请求中添加 `exFlag` 标志即可。在调用 课程和教师服务后模拟异常进行回滚操作

[source,http]
----
POST http://localhost:18002/student/score/add?ex
Content-Type: application/json

{
  "sname": "田电",
  "mapList": [
    {
      "cname": "语文",
      "tname": "张三",
      "score": 69
    },
    {
      "cname": "数学",
      "tname": "李四",
      "score": 89
    },
    {
      "cname": "英语",
      "tname": "王五",
      "score": 66
    }
  ]
}
----

4、查看结果 `http://localhost:18002/student/name/田电`，结果如下

[source,json]
----
{
"sname": "田电",
"mapList": []
}
----


== 源码

https://github.com/jcohy-sample/spring-sample/tree/main/spring-cloud/spring-cloud-provider-tm[源码] 和 https://github.com/jcohy-sample/spring-sample/blob/main/spring-cloud/spring-cloud-provider-tm/http/provider.http[http 请求文件]

== 参考

https://xxx[]
