server:
  port: 19001

eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://localhost:17001/eureka
#       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: provider-course18001
    prefer-ip-address: true     #访问路径可以显示 IP 地址
 
info: 
  app.name: provider-course
  company.name: www.jcohy.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

